### ISSUE TITLE
Cities Towns Locations Link not working

### ISSUE THREAD

**Issue by adtde** [agrc/gis.utah.gov#1026]
_Please be comfortable to submit an issue if you have a question, want to ask to post new content or if the website isn't working properly for you._

## Issue description
I am trying to access GIS data for Cities, Towns, and locations, but I'm running into a broken link.

#### What page is the problem visible
https://gis.utah.gov/data/location/

#### Expected result
I expected: click on the "Cities Towns Locations" link and navigate to where the data is.

#### Actual result
Instead: I get a broken link and the data is not found. The link takes me to: https://drive.google.com/drive/folders/0ByStJjVZ7c7meDNmdFRpeWVwbTA

_You can drag and drop or paste screen shots from your clipboard to here. Please do it's very helpful!_

**Comment by steveoh** [comment]
I see the files in the drive link you posted. Is your network blocking drive downloads? Where are you located and who do you work for?

**Comment by steveoh** [comment]
This issue will be closed if no further information can be gathered. @adtde will you please respond to the questions?

**Comment by adtde** [comment]
I work for Dominion Energy. It appears that my network is blocking Google Drive so that is the problem. Google Drive is blocked for security reasons by IT. I apologize for not seeing your earlier response (my email filters thought it was spam...). Looks like the problem is on my end and not yours and will likely continue since I don't think my company's corporate IT department is going to unblock Google Drive any time soon...

Is there a reason why some links like "Cities Towns Locations" (and some others) point to Google Drive, but all the other links located on the URL https://gis.utah.gov/data/location/ do not? Just curious...

**Comment by steveoh** [comment]
@adtde all of the data downloads that we host are via google drive. I do not follow what other links on location do not. Ultimately, to download the data, it will be via a drive link. 

@adtde hopefully you can get an exception from IT to download our data. Otherwise, you can try our [open data](http://opendata.gis.utah.gov/search?q=location) website. There is some duplication there. Finally an email to agrc@utah.gov asking for the data would be the final solution.

Since we know the issue and I have given you a few options, I will close this issue. Thank you for bringing it up.

**Comment by adtde** [comment]
Nevermind on the hosting of the data. You are correct. Thanks for the open data website link.
