### ISSUE TITLE
Fix/Update ZipCode POBoxes and Zip Code Areas Data Pages

### ISSUE THREAD

**Issue by jacobdadams** [agrc/gis.utah.gov#1805]
_Please be comfortable to submit an issue if you have a question, want to ask to post new content or if the website isn't working properly for you._

## Issue description
https://gis.utah.gov/data/location/u-s-postal-service/ has a mis-named section for location.zip_code_po_boxes and an out-of-date section for boundaries.zip_code_areas (which duplicates the section from /data/boundaries/zip-codes).

#### What page is the problem visible
https://gis.utah.gov/data/location/u-s-postal-service/

_You can drag and drop or paste screen shots from your clipboard to here. Please do it's very helpful!_

**Comment by steveoh** [comment]
We can cross reference it from location since you looked there but I think it's permanent home should be in boundaries and added as an item to https://gis.utah.gov/data/boundaries/zip-codes/ specifically

**Comment by jacobdadams** [comment]
Issue submitted during a conversation to remember; further investigation shows it exists in https://gis.utah.gov/data/location/u-s-postal-service/ but is mislabeled. I'll update the issue accordingly.

**Comment by jacobdadams** [comment]
Ok, here's the current situation:

Boundaries/Zip Codes(https://gis.utah.gov/data/boundaries/zip-codes/):
- Up-to-date description of `boundaries.zip_code_areas`

Location/United States Postal Service (https://gis.utah.gov/data/location/u-s-postal-service/):
- Description for `location.zip_code_po_boxes`
- Out-of-date description for `boundaries.zip_code_areas`

Society main page (https://gis.utah.gov/data/society/):
- Direct link to open data page for Post Office locations

Should I just copy the `location.zip_code_po_boxes` section to data/boundaries/zip-codes/ and rename/update it, and then replace data/location/u-s-postal-service/ with a link to the boundaries page?

**Comment by steveoh** [comment]
Uh-oh. Jakes looking under the rug. 

![uhohh](https://media.giphy.com/media/5n26EW5p9lWGafPdbf/giphy-downsized.gif)

You are going to find all sorts of "issues" with the category index pages and what is left of the data packages. Why some datasets have a data page and others don't is a good question I don't have an answer for. We should sort this all out at some point but in bite size chunks please.

The original idea was that someone looking for post offices they might also want zip codes. It's the classic people who bought this also bought that type of upsell. To increase data awareness and simplify the download process we created the package pages. All the items in a package could be downloaded as a single geodatabase or zip file. Those bundles left with the drive downloads but we kept the package pages around since they contain metadata that isn't available in open data.

There isn't a 1:1 mapping between the SGID and the package pages or even the category index pages.

I like the discoverability aspect of the package pages. Since we have so much data, I think it helps to tell people what other data relates to what they are interested in. 

With that in mind, I think I would suggest

1. Update the `u-s-postal-service` page to reference the `utah-post-offices` data in it's own section.
   - update the description yada yada
1. Add a new section for the `location.zip_code_po_boxes` on the u-s-postal-service` page since we already have the description and everything set up
   - or just remove it and add a related resource to the utah post offices section
1. Update the description on the zip codes page to be accurate
1. Link to the gis.utah.gov page from the society page

**Comment by eneemann** [comment]
I think I mostly agree with @steveoh here.  We can keep the ` boundaries/zip-codes ` page (it has 5 times more hits), but update the `/location/u-s-postal-service` page to have all 3 relevant datasets there, by adding `utah-post-offices`:
- `location.utah-post-offices`
- `location.utah-zip-code-po-boxes`
- `boundaries.utah-zip-code-areas`

We should just match the descriptions for `zip-code-areas`, using the one that already exists on the `boundaries/zip-codes/` page.  Then on the `data/society/` page link 'Post Offices' to `/location/u-s-postal-service` as Steve mentions.

**Comment by eneemann** [comment]
I'll get to work on cleaning this up
