### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by steveoh** [agrc/gis.utah.gov#265]
The `agrc.github.io` repository name was an unfortunate side affect of using github pages. Since we no longer use github pages, what do you think about renaming this to:

1. website
1. gis portal
1. gis.utah.gov
1. _write in_

Please comment with your vote or write in.

Github will handle redirecting to the new name so I think there is little downside of making this change.
@BGranberg, @jpechmann, @stdavis, @rkelson, @brigsz  thoughts?

**Comment by BGranberg** [comment]
3

-------
Bert Granberg
Utah AGRC
@BertAGRC
http://gis.utah.gov

On Oct 19, 2016, at 5:59 PM, steveoh <notifications@github.com> wrote:

The agrc.github.io repository name was an unfortunate side affect of using
github pages. Since we no longer use github pages, what do you think about
renaming this to:

   1. website
   2. gis portal
   3. gis.utah.gov
   4. _write in _

Please comment with your vote or write in.

Github will handle redirecting to the new name so I think there is little
downside of making this change.
@BGranberg <https://github.com/BGranberg>, @jpechmann
<https://github.com/jpechmann>, @stdavis <https://github.com/stdavis>,
@rkelson <https://github.com/rkelson>, @brigsz <https://github.com/brigsz>
thoughts?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/agrc/agrc.github.io/issues/265>, or mute the thread

**Comment by stdavis** [comment]
I agree. #3 would be my first choice followed by #1.
